.pragma library

const MESSAGES = {
    "{percent}% left": "Осталось {percent}%",
    "{percent}% used": "Использовано {percent}%",
    "{percent}% left of {capacity}%": "Осталось {percent}% из {capacity}%",
    "{percent}% used of {capacity}%": "Использовано {percent}% из {capacity}%",
    "At this pace: ~{percent}% of {capacity}% left at reset": "При текущем темпе к сбросу останется ~{percent}% из {capacity}%",
    "At this pace: ~{percent}% of {capacity}% used at reset": "При текущем темпе к сбросу будет использовано ~{percent}% из {capacity}%",
    "At this pace: runs out before reset": "При текущем темпе закончится до сброса",
    "{count} account": ["{count} аккаунт", "{count} аккаунта", "{count} аккаунтов"],
    "S": "С",
    "W": "Н",
    "Session": "Сессия",
    "Weekly": "Неделя",
    "Sun": "вс",
    "Mon": "пн",
    "Tue": "вт",
    "Wed": "ср",
    "Thu": "чт",
    "Fri": "пт",
    "Sat": "сб",
    "Jan": "янв",
    "Feb": "фев",
    "Mar": "мар",
    "Apr": "апр",
    "May": "мая",
    "Jun": "июн",
    "Jul": "июл",
    "Aug": "авг",
    "Sep": "сен",
    "Oct": "окт",
    "Nov": "ноя",
    "Dec": "дек",
    "{month} {day}": "{day} {month}",
    "{days}d {hours}h": "{days} д {hours} ч",
    "{hours}h {minutes}m": "{hours} ч {minutes} мин",
    "{minutes}m": "{minutes} мин",
    "{minutes}m {seconds}s": "{minutes} мин {seconds} с",
    "{seconds}s": "{seconds} с",
    "today at {time}": "сегодня в {time}",
    "tomorrow at {time}": "завтра в {time}",
    "{day} at {time}": "{day} в {time}",
    "resets {moment}": "сброс {moment}",
    "resets soon": "скоро сброс",
    "reset pending": "ожидается сброс",
    "resets in {duration}": "сброс через {duration}",
    "Not started": "Не начато",
    "~{percent}% spare": "~{percent}% запаса",
    "Limit soon": "Скоро лимит",
    "Limit in {duration}": "Лимит через {duration}",
    "Limit reached": "Лимит исчерпан",
    "Over pace": "Темп выше нормы",
    "At this pace: runs out any minute": "При текущем темпе: закончится с минуты на минуту",
    "runs out in {duration}": "закончится через {duration}",
    "At this pace: {runsOut}": "При текущем темпе: {runsOut}",
    "At this pace: {runsOut} · {resets}": "При текущем темпе: {runsOut} · {resets}",
    "At this pace: ~{percent}% used at reset": "При текущем темпе к сбросу будет использовано ~{percent}%",
    "At this pace: ~{percent}% left at reset": "При текущем темпе к сбросу останется ~{percent}%",
    "Next update in <1m": "Обновление через <1 мин",
    "Next update in {duration}": "Обновление через {duration}",
    "just now": "только что",
    "{duration} ago": "{duration} назад",
    "{tokens} token": ["{tokens} токен", "{tokens} токена", "{tokens} токенов"],
    "No data": "Нет данных",
    "{cost} · {tokens} tokens": "{cost} · {tokens} токенов",
    "{cost} · {tokens}": "{cost} · {tokens}",
    " · some models unpriced": " · часть моделей без цены",
    "{date} · no usage": "{date} · нет использования",
    "{date} · {tokens} tokens · {cost}": "{date} · {tokens} токенов · {cost}",
    "Today": "Сегодня",
    "Yesterday": "Вчера",
    "Last 30 Days": "30 дней",
    "30 Days": "30 дней",
    "Retry": "Повторить",
    "Signed out of {provider}": "Выполнен выход из {provider}",
    "Sign in again through Headroom (Settings → Accounts → Add Account) or remove the account.": "Войдите снова через Headroom (Настройки → Аккаунты → Добавить аккаунт) или удалите аккаунт.",
    "Couldn't refresh {provider}": "Не удалось обновить {provider}",
    "Offline": "Нет сети",
    "Offline — last update {time}": "Нет сети — последнее обновление в {time}",
    "Service not running": "Служба не запущена",
    "Connecting…": "Подключение…",
    "Updating…": "Обновление…",
    "Updated {time}": "Обновлено в {time}",
    "No usage limits to show": "Нет лимитов для показа",
    "Some models have no public price yet.": "У некоторых моделей пока нет публичной цены.",
    "Estimated from local logs and public pricing.": "Оценка по локальным журналам и публичным ценам.",
    "No usage in the last 30 days": "Нет использования за последние 30 дней",
    "Peak {tokens} tokens on {date}": "Пик: {tokens} токенов, {date}",
    "unpriced": "без цены",
    "Other ({count})": "Другие ({count})",
    "Total Spend": "Всего потрачено",
    "No usage in this period": "Нет использования за этот период",
    "Usage Trend": "Динамика",
    "Outdated": "Устарело",
    "Last updated {ago}": "Обновлено {ago}",
    "Refresh failed": "Не удалось обновить",
    "Partly unpriced, cost leaves it out": "Частично без цены, в стоимость не входит",
    "Refresh": "Обновить",
    "Settings": "Настройки",
    "No active subscription": "Подписка неактивна",
    "Limits aren't available for this account. Renew the plan or sign in with another account.": "Данные о лимитах недоступны. Продлите подписку или войдите в другой аккаунт.",
    "Try again": "Повторить",
    "Starting…": "Запуск…",
    "Start service": "Запустить службу",
    "Check again": "Проверить снова",
    "Headroom service isn't running": "Служба Headroom не запущена",
    "Couldn't read Headroom's state": "Не удалось прочитать состояние Headroom",
    "Start it to see your usage limits here.": "Запустите её, чтобы видеть здесь свои лимиты.",
    "No AI coding tools found.": "ИИ-инструменты для программирования не найдены.",
    "Loading…": "Загрузка…",
    "Deletes the sign-in Headroom created for this account": "Удаляет вход, который Headroom создал для этого аккаунта",
    "Headroom deletes the sign-in it created for this account. The account itself is not affected.": "Headroom удалит созданный им вход для этого аккаунта. Сам аккаунт не пострадает.",
    "Stops showing this account; the {provider} CLI stays signed in": "Скрывает аккаунт из Headroom; вход в CLI {provider} сохраняется",
    "Headroom will stop showing this account. The {provider} CLI stays signed in; you can sign in again through Headroom.": "Headroom перестанет показывать этот аккаунт. Вход в CLI {provider} сохранится; войти снова можно через Headroom.",
    "Sign in…": "Войти…",
    "Press Enter to close this window": "Нажмите Enter, чтобы закрыть это окно",
    "Signs in with the {program} CLI in a terminal": "Вход через CLI {program} в терминале",
    "Asks for an API key in a terminal": "Запросит API-ключ в терминале",
    "Found automatically": "Находится автоматически",
    "Unreadable state from the Headroom service: {reason}": "Не удалось разобрать состояние от службы Headroom: {reason}",
    "Unexpected state from the Headroom service": "Служба Headroom прислала состояние в неожиданном формате",
    "Headroom service speaks state version {version}, expected {expected}": "Служба Headroom использует версию состояния {version}, ожидалась {expected}",
    "Unreadable provider list from the Headroom service: {reason}": "Не удалось разобрать список сервисов от службы Headroom: {reason}",
    "Unexpected provider list from the Headroom service": "Служба Headroom прислала список сервисов в неожиданном формате",
    "Headroom service speaks provider list version {version}, expected {expected}": "Служба Headroom использует версию списка сервисов {version}, ожидалась {expected}",
    "Unexpected provider id {provider}": "Недопустимый идентификатор сервиса {provider}",
    "Unexpected account id {account}": "Недопустимый идентификатор аккаунта {account}",
    "Copied": "Скопировано",
    "Copy": "Копировать",
    "What's new": "Что нового",
    "Update": "Обновить",
    "How to update": "Как обновить",
    "Release notes": "Примечания к выпуску",
    "Headroom {version} is available": "Доступна версия Headroom {version}",
    "Couldn't find the headroom command": "Не удалось найти команду headroom",
    "The update stopped before it finished": "Обновление прервалось и не завершилось",
    "Updating Headroom…": "Обновляем Headroom…",
    "Updated — log out and back in to finish": "Обновлено — выйдите из сеанса и войдите снова",
    "Updated to {version}": "Обновлено до {version}",
    "Updated": "Обновлено",
    "Credits": "Кредиты",
    "Extra usage": "Доп. использование",
    "Balance": "Баланс",
    "Vouchers": "Ваучеры",
    "Cash": "Денежный баланс",
    "Credit balance": "Кредиты",
    "Organization credits": "Кредиты организации",
    "Point balance": "Баланс баллов",
    "Bonus credits": "Бонусные кредиты",
    "Monthly credits": "Кредиты на месяц",
    "Weekly limit shared with Codex Cloud": "Недельный лимит общий с Codex Cloud",
    "Offline — showing limits from local logs.": "Нет сети — лимиты по локальным журналам.",
    "Sign-in expired — open Codex to sign in again. Showing limits from local logs.": "Вход истёк — откройте Codex, чтобы войти снова. Лимиты по локальным журналам.",
    "Credit balance needs a management key": "Для баланса кредитов нужен ключ управления",
    "Credit balance is unavailable right now": "Баланс кредитов сейчас недоступен",
    "No Cline credits left.": "Кредиты Cline закончились.",
    "Legacy Grok billing has no weekly pool.": "В старом тарифе Grok нет недельного лимита.",
    "Ollama reports no Cloud limits for this account yet.": "Ollama пока не сообщает лимиты Cloud для этого аккаунта.",
    "Could not read the Ollama plan; the usage above is up to date.": "Не удалось прочитать тариф Ollama; использование выше актуально.",
    "Antigravity reports no quota pools for this account.": "Antigravity не сообщает лимиты для этого аккаунта.",
    "The keyring that holds the Antigravity sign-in is locked. Unlock it or start Antigravity.": "Связка ключей со входом в Antigravity заблокирована. Разблокируйте её или запустите Antigravity.",
    "Kilo credits are used up": "Кредиты Kilo закончились",
    "Unlimited credits": "Безлимитные кредиты",
    "No monthly credits on this plan": "В этом тарифе нет ежемесячных кредитов",
    "Balance is not enough for API calls": "Баланса не хватает для вызовов API",
    "Balance is used up; API calls fail until you top up": "Баланс исчерпан — вызовы API не пройдут, пока вы не пополните счёт",
    "Balance is used up; API requests fail until you top up": "Баланс исчерпан — запросы к API не пройдут, пока вы не пополните счёт",
    "Cash balance is negative: the account is in debt": "Денежный баланс отрицательный — на счёте долг",
    "Extra usage on, cap {amount}": "Доп. использование включено, предел {amount}",
    "{plan} renews on {date} (UTC).": "{plan} продлевается {date} (UTC).",
    "{plan} ends on {date} (UTC).": "{plan} заканчивается {date} (UTC).",
    "Sign in again…": "Войти снова…",
    "Copy command": "Скопировать команду",
    "Run `{command}` in a terminal — Headroom picks it up automatically.": "Выполните `{command}` в терминале — Headroom подхватит вход сам.",
    "Headroom's sign-in for this account has expired. Sign in again or remove the account.": "Вход Headroom для этого аккаунта истёк. Войдите снова или удалите аккаунт.",
    "checked {ago}": "проверено {ago}",
    "You're up to date · Headroom {version} · {checked}": "У вас последняя версия · Headroom {version} · {checked}",
    "You're up to date · Headroom {version}": "У вас последняя версия · Headroom {version}",
    "Update available": "Доступно обновление",
    "Update available · {checked}": "Доступно обновление · {checked}",
    "Couldn't check for updates": "Не удалось проверить обновления",
    "Couldn't check for updates · last checked {ago}": "Не удалось проверить обновления · последняя проверка {ago}",
    "GitHub limits update checks · try again later": "GitHub ограничил проверки · попробуйте позже",
    "GitHub limits update checks · try again in {duration}": "GitHub ограничил проверки · попробуйте через {duration}",
    "Update checks are off": "Проверка обновлений выключена",
    "Headroom {version} · not checked yet": "Headroom {version} · ещё не проверялось",
    "Needs a newer Headroom service": "Нужна более новая служба Headroom",
    "Unexpected answer from the Headroom service": "Служба Headroom прислала ответ в неожиданном формате",
    "{tokens} tokens": "{tokens} токенов",
    "{cost}/MTok": "{cost}/млн ток.",
    "No project": "Без проекта",
    "Cost per MTok": "Цена за 1 млн",
    "Degraded performance": "Снижена производительность",
    "Partial outage": "Частичный сбой",
    "Major outage": "Серьёзный сбой",
    "Maintenance": "Техработы",
    "Investigating": "Выясняем причину",
    "Identified": "Причина найдена",
    "Monitoring": "Наблюдаем",
    "In progress": "Идут работы",
    "Verifying": "Проверяем",
    "7 Days": "7 дней",
    "{count} more": ["Ещё {count}", "Ещё {count}", "Ещё {count}"],
    "Open folder": "Открыть папку",
    "Refresh {provider}": "Обновить {provider}",
    "Hide from popup": "Скрыть из окна",
    "Always show": "Показывать всегда",
    "Share as image…": "Поделиться картинкой…",
    "Copy as text": "Копировать текстом",
    "Show accounts that are not pinned": "Показать незакреплённые аккаунты",
    "Not pinned": "Не закреплены",
    "Show less": "Свернуть",
    "Saved to Pictures/Headroom": "Сохранено в Изображения/Headroom",
    "Could not save the image": "Не удалось сохранить картинку",
    "Copied as text": "Скопировано текстом",
    "Status page": "Страница статуса",
    "Open dashboard": "Открыть панель управления",
    "Usage page": "Страница использования",
    "{percent}% · {tokens} tokens": "{percent}% · {tokens} токенов",
    "Other": "Другие",
    "Models after the top five are folded into Other.": "Модели после первых пяти собраны в «Другие».",
    "{day} {time}": "{day} {time}",
    "soon": "скоро",
    "Click to show what is left": "Нажмите, чтобы показать остаток",
    "Click to show used": "Нажмите, чтобы показать использованное",
    "Click to show the countdown": "Нажмите, чтобы показать обратный отсчёт",
    "Click to show the reset time": "Нажмите, чтобы показать время сброса",
    "Updated {ago}": "Обновлено {ago}",
    "Next at {time}": "Следующее в {time}",
    "Outdated · updated {ago}": "Устарело · обновлено {ago}",
    "Offline — retrying in {duration}": "Нет сети — повтор через {duration}",
    "Live — every {duration} · {names}": "Вживую — каждые {duration} · {names}",
    "{names} wrote new usage in the last 10 minutes, so it is checked every {duration}. Back to the usual interval after 10 minutes without activity.": "{names}: новые записи использования за последние 10 минут, поэтому проверка идёт каждые {duration}. Обычный интервал вернётся после 10 минут без активности.",
    "Started {ago}": "Началось {ago}",
    "of {capacity}% · {window} · {reset}": "из {capacity}% · {window} · {reset}",
    "used": "использовано",
    "left": "осталось",
    "{day} {month} {year}": "{day} {month} {year}",
    "{provider} limits · {date}": "Лимиты {provider} · {date}",
    "Dollars, from local logs and public prices": "Доллары по локальным журналам и публичным ценам",
    "Total Tokens": "Всего токенов",
    "Input, output and cache tokens": "Входные, выходные и кэшированные токены",
    "Spend divided by million tokens": "Расходы на миллион токенов",
    "tokens": "токенов",
    "blended": "в среднем",
    "{count} model": ["{count} модель", "{count} модели", "{count} моделей"],
    "{count} project": ["{count} проект", "{count} проекта", "{count} проектов"],
    "Paused": "Пауза",
    "Paused · lasts ≈{duration} of work": "Пауза · хватит ≈{duration} работы",
    "{minutes} min": "{minutes} мин",
    "{hours} h": "{hours} ч",
    "{days} d": "{days} д",
    "Sign in": "Войти"
};
