.pragma library

const MESSAGES = {
    "{percent}% left": "Осталось {percent}%",
    "{percent}% used": "Использовано {percent}%",
    "{percent}% left of {capacity}%": "Осталось {percent}% из {capacity}%",
    "{percent}% used of {capacity}%": "Использовано {percent}% из {capacity}%",
    "At this pace: ~{percent}% of {capacity}% left at reset": "При текущем темпе к сбросу останется ~{percent}% из {capacity}%",
    "At this pace: ~{percent}% of {capacity}% used at reset": "При текущем темпе к сбросу будет использовано ~{percent}% из {capacity}%",
    "At this pace: runs out before reset": "При текущем темпе закончится до сброса",
    "{count} account": ["{count} аккаунт", "{count} аккаунта", "{count} аккаунтов"],
    "Combine accounts of the same provider": "Объединять аккаунты одного сервиса",
    "Show one card per provider and add up the limits of its accounts": "Одна карточка на сервис, лимиты его аккаунтов складываются",
    "S": "С",
    "W": "Н",
    "Session": "Сессия",
    "Weekly": "Неделя",
    "Sun": "вс",
    "Mon": "пн",
    "Tue": "вт",
    "Wed": "ср",
    "Thu": "чт",
    "Fri": "пт",
    "Sat": "сб",
    "Jan": "янв",
    "Feb": "фев",
    "Mar": "мар",
    "Apr": "апр",
    "May": "мая",
    "Jun": "июн",
    "Jul": "июл",
    "Aug": "авг",
    "Sep": "сен",
    "Oct": "окт",
    "Nov": "ноя",
    "Dec": "дек",
    "{month} {day}": "{day} {month}",
    "{days}d {hours}h": "{days} д {hours} ч",
    "{hours}h {minutes}m": "{hours} ч {minutes} мин",
    "{minutes}m": "{minutes} мин",
    "{minutes}m {seconds}s": "{minutes} мин {seconds} с",
    "{seconds}s": "{seconds} с",
    "today at {time}": "сегодня в {time}",
    "tomorrow at {time}": "завтра в {time}",
    "{day} at {time}": "{day} в {time}",
    "resets {moment}": "сброс {moment}",
    "resets soon": "скоро сброс",
    "reset pending": "ожидается сброс",
    "resets in {duration}": "сброс через {duration}",
    "Not started": "Не начато",
    "~{percent}% spare": "~{percent}% запаса",
    "Limit soon": "Скоро лимит",
    "Limit in {duration}": "Лимит через {duration}",
    "Limit reached": "Лимит исчерпан",
    "Over pace": "Темп выше нормы",
    "At this pace: runs out any minute": "При текущем темпе: закончится с минуты на минуту",
    "runs out in {duration}": "закончится через {duration}",
    "At this pace: {runsOut}": "При текущем темпе: {runsOut}",
    "At this pace: {runsOut} · {resets}": "При текущем темпе: {runsOut} · {resets}",
    "At this pace: ~{percent}% used at reset": "При текущем темпе к сбросу будет использовано ~{percent}%",
    "At this pace: ~{percent}% left at reset": "При текущем темпе к сбросу останется ~{percent}%",
    "Next update in <1m": "Обновление через <1 мин",
    "Next update in {duration}": "Обновление через {duration}",
    "just now": "только что",
    "{duration} ago": "{duration} назад",
    "{tokens} token": ["{tokens} токен", "{tokens} токена", "{tokens} токенов"],
    "No data": "Нет данных",
    "{cost} · {tokens} tokens": "{cost} · {tokens} токенов",
    "{cost} · {tokens}": "{cost} · {tokens}",
    " · some models unpriced": " · часть моделей без цены",
    "{date} · no usage": "{date} · нет использования",
    "{date} · {tokens} tokens · {cost}": "{date} · {tokens} токенов · {cost}",
    "Today": "Сегодня",
    "Yesterday": "Вчера",
    "Last 30 Days": "30 дней",
    "30 Days": "30 дней",
    "Retry": "Повторить",
    "Signed out of {provider}": "Выполнен выход из {provider}",
    "Sign in again through Headroom (Settings → Accounts → Add Account) or remove the account.": "Войдите снова через Headroom (Настройки → Аккаунты → Добавить аккаунт) или удалите аккаунт.",
    "Couldn't refresh {provider}": "Не удалось обновить {provider}",
    "Offline": "Нет сети",
    "Offline — last update {time}": "Нет сети — последнее обновление в {time}",
    "Service not running": "Служба не запущена",
    "Connecting…": "Подключение…",
    "Updating…": "Обновление…",
    "Updated {time}": "Обновлено в {time}",
    "No usage limits to show": "Нет лимитов для показа",
    "Some models have no public price yet.": "У некоторых моделей пока нет публичной цены.",
    "Estimated from local logs and public pricing.": "Оценка по локальным журналам и публичным ценам.",
    "No usage in the last 30 days": "Нет использования за последние 30 дней",
    "Peak {tokens} tokens on {date}": "Пик: {tokens} токенов, {date}",
    "unpriced": "без цены",
    "Other ({count})": "Другие ({count})",
    "Total spend": "Общие расходы",
    "Spend ring for all tools at the top": "Кольцо расходов по всем инструментам вверху",
    "Per-account spend": "Расходы по аккаунтам",
    "Today, yesterday and 30 days under each account": "Сегодня, вчера и за 30 дней под каждым аккаунтом",
    "Usage trend": "Динамика использования",
    "Daily token bars for the last 30 days": "Столбцы токенов по дням за последние 30 дней",
    "Pace forecast": "Прогноз темпа",
    "Where each limit lands at the current pace": "Чем закончится каждый лимит при текущем темпе",
    "Almost out": "Почти закончился",
    "A limit drops under 10% left": "Остаток лимита опускается ниже 10%",
    "Cutting it close": "Впритык",
    "The pace says a limit will barely last until reset": "По темпу лимита едва хватит до сброса",
    "Will run out": "Закончится",
    "The pace says a limit runs out before it resets": "По темпу лимит закончится раньше сброса",
    "Limit reset": "Лимит сброшен",
    "A limit that was running low resets": "Сбрасывается лимит, который был на исходе",
    "System": "Как в системе",
    "Light": "Светлая",
    "Dark": "Тёмная",
    "Left": "Остаток",
    "Used": "Использовано",
    "Countdown": "Обратный отсчёт",
    "Exact time": "Точное время",
    "Percent": "Проценты",
    "Provider + limit": "Сервис + лимит",
    "{count} second": ["{count} секунда", "{count} секунды", "{count} секунд"],
    "Every minute": ["Каждую {count} минуту", "Каждые {count} минуты", "Каждые {count} минут"],
    "Auto — most critical": "Авто — самый критичный",
    "Pinned limit (not available now)": "Закреплённый лимит (сейчас недоступен)",
    "Total Spend": "Всего потрачено",
    "No usage in this period": "Нет использования за этот период",
    "Usage Trend": "Динамика",
    "Outdated": "Устарело",
    "Last updated {ago}": "Обновлено {ago}",
    "Refresh failed": "Не удалось обновить",
    "Click to switch between left and used": "Нажмите, чтобы переключить остаток и использование",
    "Click to switch between countdown and exact time": "Нажмите, чтобы переключить отсчёт и точное время",
    "Partly unpriced, cost leaves it out": "Частично без цены, в стоимость не входит",
    "Refresh": "Обновить",
    "Settings": "Настройки",
    "No active subscription": "Подписка неактивна",
    "Limits aren't available for this account. Renew the plan or sign in with another account.": "Данные о лимитах недоступны. Продлите подписку или войдите в другой аккаунт.",
    "Try again": "Повторить",
    "Starting…": "Запуск…",
    "Start service": "Запустить службу",
    "Check again": "Проверить снова",
    "Headroom service isn't running": "Служба Headroom не запущена",
    "Couldn't read Headroom's state": "Не удалось прочитать состояние Headroom",
    "Start it to see your usage limits here.": "Запустите её, чтобы видеть здесь свои лимиты.",
    "No AI coding tools found.": "ИИ-инструменты для программирования не найдены.",
    "Loading…": "Загрузка…",
    "General": "Основные",
    "Accounts": "Аккаунты",
    "Notifications": "Уведомления",
    "Appearance": "Оформление",
    "Theme": "Тема",
    "The popup follows the system unless you pick one": "Всплывающее окно следует системе, если не выбрать тему",
    "Language": "Язык",
    "Translucent popup": "Полупрозрачное окно",
    "Let the blurred desktop show through the popup": "Размытый рабочий стол просвечивает сквозь окно",
    "Popup": "Всплывающее окно",
    "Show values as": "Показывать значения",
    "Click a reading in the popup to switch": "Нажмите на значение в окне, чтобы переключить",
    "Reset time": "Время сброса",
    "Click a reset time in the popup to switch": "Нажмите на время сброса в окне, чтобы переключить",
    "Top Panel": "Верхняя панель",
    "Panel limit": "Лимит на панели",
    "The limit shown next to the clock": "Лимит, который показывается рядом с часами",
    "Panel label": "Подпись на панели",
    "Sections": "Разделы",
    "Updates": "Обновления",
    "Refresh interval": "Интервал обновления",
    "How often the service asks each provider": "Как часто служба опрашивает каждый сервис",
    "Notify Me When": "Уведомлять, когда",
    "Hidden accounts and hidden limits never notify.": "Скрытые аккаунты и скрытые лимиты не присылают уведомлений.",
    "added in Headroom": "добавлен в Headroom",
    "Show in the panel and popup": "Показывать на панели и во всплывающем окне",
    "Label": "Название",
    "Apply": "Применить",
    "Limits": "Лимиты",
    "No data yet": "Пока нет данных",
    "Remove from Headroom": "Удалить из Headroom",
    "Deletes the sign-in Headroom created for this account": "Удаляет вход, который Headroom создал для этого аккаунта",
    "Remove": "Удалить",
    "Remove {name}?": "Удалить {name}?",
    "Headroom deletes the sign-in it created for this account. The account itself is not affected.": "Headroom удалит созданный им вход для этого аккаунта. Сам аккаунт не пострадает.",
    "Stops showing this account; the {provider} CLI stays signed in": "Скрывает аккаунт из Headroom; вход в CLI {provider} сохраняется",
    "Headroom will stop showing this account. The {provider} CLI stays signed in; you can sign in again through Headroom.": "Headroom перестанет показывать этот аккаунт. Вход в CLI {provider} сохранится; войти снова можно через Headroom.",
    "Cancel": "Отмена",
    "Add {provider} account": "Добавить аккаунт {provider}",
    "Label (optional)": "Название (необяз.)",
    "Sign in…": "Войти…",
    "A terminal window opened. Finish signing in there; the account shows up here when it is done.": "Открылось окно терминала. Завершите вход там — аккаунт появится здесь, когда всё будет готово.",
    "Press Enter to close this window": "Нажмите Enter, чтобы закрыть это окно",
    "Couldn't remove the account": "Не удалось удалить аккаунт",
    "No terminal found. Install xdg-terminal-exec or Konsole, or run \"headroom accounts add\" yourself.": "Терминал не найден. Установите xdg-terminal-exec или Konsole либо запустите «headroom accounts add» сами.",
    "Drag to reorder. Hidden accounts keep updating but leave the panel and notifications.": "Перетаскивайте, чтобы изменить порядок. Скрытые аккаунты продолжают обновляться, но не показываются на панели и в уведомлениях.",
    "No accounts yet": "Пока нет аккаунтов",
    "Sign in with a supported CLI, or add an account below.": "Войдите через поддерживаемый CLI или добавьте аккаунт ниже.",
    "Add Account": "Добавить аккаунт",
    "Pick a service. Accounts added here never touch the one your CLI uses.": "Выберите сервис. Аккаунты, добавленные здесь, не затрагивают тот, что использует ваш CLI.",
    "Signs in with the {program} CLI in a terminal": "Вход через CLI {program} в терминале",
    "Asks for an API key in a terminal": "Запросит API-ключ в терминале",
    "Found automatically": "Находится автоматически",
    "Add API key…": "Добавить API-ключ…",
    "Rescan": "Искать снова",
    "Get a key…": "Получить ключ…",
    "A terminal window opened. Paste the API key there; the account shows up here when it is done.": "Открылось окно терминала. Вставьте туда API-ключ — аккаунт появится здесь, когда всё будет готово.",
    "Looking for accounts. New ones show up here in a moment.": "Ищем аккаунты. Новые появятся здесь через мгновение.",
    "No providers available": "Нет доступных сервисов",
    "Unreadable state from the Headroom service: {reason}": "Не удалось разобрать состояние от службы Headroom: {reason}",
    "Unexpected state from the Headroom service": "Служба Headroom прислала состояние в неожиданном формате",
    "Headroom service speaks state version {version}, expected {expected}": "Служба Headroom использует версию состояния {version}, ожидалась {expected}",
    "Unreadable settings from the Headroom service: {reason}": "Не удалось разобрать настройки от службы Headroom: {reason}",
    "Unexpected settings from the Headroom service": "Служба Headroom прислала настройки в неожиданном формате",
    "Unreadable provider list from the Headroom service: {reason}": "Не удалось разобрать список сервисов от службы Headroom: {reason}",
    "Unexpected provider list from the Headroom service": "Служба Headroom прислала список сервисов в неожиданном формате",
    "Headroom service speaks provider list version {version}, expected {expected}": "Служба Headroom использует версию списка сервисов {version}, ожидалась {expected}",
    "Unexpected provider id {provider}": "Недопустимый идентификатор сервиса {provider}",
    "Unexpected account id {account}": "Недопустимый идентификатор аккаунта {account}",
    "Copied": "Скопировано",
    "Copy": "Копировать",
    "Data refresh": "Обновление данных",
    "Check for updates": "Проверять обновления",
    "Once a day, asks GitHub for the latest release. Nothing else is sent.": "Раз в день спрашивает у GitHub последнюю версию. Больше ничего не отправляется.",
    "What's new": "Что нового",
    "Update": "Обновить",
    "How to update": "Как обновить",
    "Release notes": "Примечания к выпуску",
    "Headroom {version} is available": "Доступна версия Headroom {version}",
    "Couldn't find the headroom command": "Не удалось найти команду headroom",
    "The update stopped before it finished": "Обновление прервалось и не завершилось",
    "Updating Headroom…": "Обновляем Headroom…",
    "Updated — log out and back in to finish": "Обновлено — выйдите из сеанса и войдите снова",
    "Updated to {version}": "Обновлено до {version}",
    "Updated": "Обновлено",
    "Credits": "Кредиты",
    "Extra usage": "Доп. использование",
    "Balance": "Баланс",
    "Vouchers": "Ваучеры",
    "Cash": "Денежный баланс",
    "Credit balance": "Кредиты",
    "Organization credits": "Кредиты организации",
    "Point balance": "Баланс баллов",
    "Bonus credits": "Бонусные кредиты",
    "Monthly credits": "Кредиты на месяц",
    "Weekly limit shared with Codex Cloud": "Недельный лимит общий с Codex Cloud",
    "Offline — showing limits from local logs.": "Нет сети — лимиты по локальным журналам.",
    "Sign-in expired — open Codex to sign in again. Showing limits from local logs.": "Вход истёк — откройте Codex, чтобы войти снова. Лимиты по локальным журналам.",
    "Credit balance needs a management key": "Для баланса кредитов нужен ключ управления",
    "Credit balance is unavailable right now": "Баланс кредитов сейчас недоступен",
    "No Cline credits left.": "Кредиты Cline закончились.",
    "Legacy Grok billing has no weekly pool.": "В старом тарифе Grok нет недельного лимита.",
    "Ollama reports no Cloud limits for this account yet.": "Ollama пока не сообщает лимиты Cloud для этого аккаунта.",
    "Could not read the Ollama plan; the usage above is up to date.": "Не удалось прочитать тариф Ollama; использование выше актуально.",
    "Antigravity reports no quota pools for this account.": "Antigravity не сообщает лимиты для этого аккаунта.",
    "The keyring that holds the Antigravity sign-in is locked. Unlock it or start Antigravity.": "Связка ключей со входом в Antigravity заблокирована. Разблокируйте её или запустите Antigravity.",
    "Kilo credits are used up": "Кредиты Kilo закончились",
    "Unlimited credits": "Безлимитные кредиты",
    "No monthly credits on this plan": "В этом тарифе нет ежемесячных кредитов",
    "Balance is not enough for API calls": "Баланса не хватает для вызовов API",
    "Balance is used up; API calls fail until you top up": "Баланс исчерпан — вызовы API не пройдут, пока вы не пополните счёт",
    "Balance is used up; API requests fail until you top up": "Баланс исчерпан — запросы к API не пройдут, пока вы не пополните счёт",
    "Cash balance is negative: the account is in debt": "Денежный баланс отрицательный — на счёте долг",
    "Extra usage on, cap {amount}": "Доп. использование включено, предел {amount}",
    "{plan} renews on {date} (UTC).": "{plan} продлевается {date} (UTC).",
    "{plan} ends on {date} (UTC).": "{plan} заканчивается {date} (UTC)."
};
