.pragma library

const MESSAGES = {
    "Combine accounts of the same provider": "Объединять аккаунты одного сервиса",
    "Show one card per provider and add up the limits of its accounts": "Одна карточка на сервис, лимиты его аккаунтов складываются",
    "Total spend": "Общие расходы",
    "Spend ring for all tools at the top": "Кольцо расходов по всем инструментам вверху",
    "Per-account spend": "Расходы по аккаунтам",
    "Today, yesterday and 30 days under each account": "Сегодня, вчера и за 30 дней под каждым аккаунтом",
    "Usage trend": "Динамика использования",
    "Daily token bars for the last 30 days": "Столбцы токенов по дням за последние 30 дней",
    "Pace forecast": "Прогноз темпа",
    "Where each limit lands at the current pace": "Чем закончится каждый лимит при текущем темпе",
    "Almost out": "Почти закончился",
    "A limit drops under 10% left": "Остаток лимита опускается ниже 10%",
    "Cutting it close": "Впритык",
    "The pace says a limit will barely last until reset": "По темпу лимита едва хватит до сброса",
    "Will run out": "Закончится",
    "The pace says a limit runs out before it resets": "По темпу лимит закончится раньше сброса",
    "Limit reset": "Лимит сброшен",
    "A limit that was running low resets": "Сбрасывается лимит, который был на исходе",
    "System": "Как в системе",
    "Light": "Светлая",
    "Dark": "Тёмная",
    "Left": "Остаток",
    "Used": "Использовано",
    "Countdown": "Обратный отсчёт",
    "Exact time": "Точное время",
    "Percent": "Проценты",
    "Provider + limit": "Сервис + лимит",
    "{count} second": ["{count} секунда", "{count} секунды", "{count} секунд"],
    "Every minute": ["Каждую {count} минуту", "Каждые {count} минуты", "Каждые {count} минут"],
    "Auto — most critical": "Авто — самый критичный",
    "Pinned limit (not available now)": "Закреплённый лимит (сейчас недоступен)",
    "General": "Основные",
    "Accounts": "Аккаунты",
    "Notifications": "Уведомления",
    "Appearance": "Оформление",
    "Theme": "Тема",
    "The popup follows the system unless you pick one": "Всплывающее окно следует системе, если не выбрать тему",
    "Language": "Язык",
    "Translucent popup": "Полупрозрачное окно",
    "Let the blurred desktop show through the popup": "Размытый рабочий стол просвечивает сквозь окно",
    "Popup": "Всплывающее окно",
    "Show values as": "Показывать значения",
    "Click a reading in the popup to switch": "Нажмите на значение в окне, чтобы переключить",
    "Reset time": "Время сброса",
    "Click a reset time in the popup to switch": "Нажмите на время сброса в окне, чтобы переключить",
    "Panel limit": "Лимит на панели",
    "The limit shown next to the clock": "Лимит, который показывается рядом с часами",
    "Panel label": "Подпись на панели",
    "Sections": "Разделы",
    "Updates": "Обновления",
    "Refresh interval": "Интервал обновления",
    "How often the service asks each provider": "Как часто служба опрашивает каждый сервис",
    "Notify Me When": "Уведомлять, когда",
    "Hidden accounts and hidden limits never notify.": "Скрытые аккаунты и скрытые лимиты не присылают уведомлений.",
    "added in Headroom": "добавлен в Headroom",
    "Show in the panel and popup": "Показывать на панели и во всплывающем окне",
    "Label": "Название",
    "Apply": "Применить",
    "Limits": "Лимиты",
    "No data yet": "Пока нет данных",
    "Remove from Headroom": "Удалить из Headroom",
    "Remove": "Удалить",
    "Remove {name}?": "Удалить {name}?",
    "Cancel": "Отмена",
    "Add {provider} account": "Добавить аккаунт {provider}",
    "Label (optional)": "Название (необяз.)",
    "A terminal window opened. Finish signing in there; the account shows up here when it is done.": "Открылось окно терминала. Завершите вход там — аккаунт появится здесь, когда всё будет готово.",
    "Couldn't remove the account": "Не удалось удалить аккаунт",
    "No terminal found. Install xdg-terminal-exec or Konsole, or run \"headroom accounts add\" yourself.": "Терминал не найден. Установите xdg-terminal-exec или Konsole либо запустите «headroom accounts add» сами.",
    "No accounts yet": "Пока нет аккаунтов",
    "Add Account": "Добавить аккаунт",
    "Pick a service. Accounts added here never touch the one your CLI uses.": "Выберите сервис. Аккаунты, добавленные здесь, не затрагивают тот, что использует ваш CLI.",
    "Add API key…": "Добавить API-ключ…",
    "Rescan": "Искать снова",
    "Get a key…": "Получить ключ…",
    "A terminal window opened. Paste the API key there; the account shows up here when it is done.": "Открылось окно терминала. Вставьте туда API-ключ — аккаунт появится здесь, когда всё будет готово.",
    "Looking for accounts. New ones show up here in a moment.": "Ищем аккаунты. Новые появятся здесь через мгновение.",
    "No providers available": "Нет доступных сервисов",
    "Unreadable settings from the Headroom service: {reason}": "Не удалось разобрать настройки от службы Headroom: {reason}",
    "Unexpected settings from the Headroom service": "Служба Headroom прислала настройки в неожиданном формате",
    "Data refresh": "Обновление данных",
    "Check for updates": "Проверять обновления",
    "Once a day, asks GitHub for the latest release. Nothing else is sent.": "Раз в день спрашивает у GitHub последнюю версию. Больше ничего не отправляется.",
    "Check now": "Проверить сейчас",
    "None": "Нет",
    "Normal": "Обычная",
    "Compact": "Компактная",
    "Automatic": "Автоматически",
    "12-hour": "12-часовой",
    "24-hour": "24-часовой",
    "One limit": "Один лимит",
    "Several limits": "Несколько лимитов",
    "Icon only": "Только значок",
    "Ring": "Кольцо",
    "Bar": "Полоса",
    "Cost": "Стоимость",
    "Tokens": "Токены",
    "Models": "Модели",
    "Projects": "Проекты",
    "Errors only": "Только ошибки",
    "Warnings": "Предупреждения",
    "Info": "Информация",
    "Debug": "Отладка",
    "Default ({percent}%)": "По умолчанию ({percent}%)",
    "Off": "Выкл.",
    "Advanced": "Дополнительно",
    "Popup cards": "Карточки в окне",
    "Star the accounts that always show their limits.": "Отметьте звёздочкой аккаунты, лимиты которых видны всегда.",
    "Collapse unstarred accounts": "Сворачивать аккаунты без звёздочки",
    "They fold into one line in the popup and open on click": "Они сворачиваются в одну строку и раскрываются по нажатию",
    "Logging": "Журнал",
    "Log level": "Уровень журнала",
    "Log file": "Файл журнала",
    "Copy path": "Скопировать путь",
    "Troubleshooting": "Диагностика",
    "Paste the diagnostics into a bug report.": "Вставьте диагностику в отчёт об ошибке.",
    "Copy diagnostics": "Скопировать диагностику",
    "Versions, desktop and account states. No tokens or emails.": "Версии, окружение и состояние аккаунтов. Без токенов и адресов почты.",
    "Reset all settings": "Сбросить все настройки",
    "Accounts stay signed in": "Вход в аккаунты сохранится",
    "Reset…": "Сбросить…",
    "Density": "Плотность",
    "Compact fits more accounts into the popup": "В компактном виде в окно помещается больше аккаунтов",
    "Time format": "Формат времени",
    "Reduce motion": "Меньше анимации",
    "Skip popup and meter animations": "Без анимации окна и шкал",
    "Faster while coding tools run": "Чаще, пока работают инструменты",
    "Every minute while a coding tool is writing usage logs": "Каждую минуту, пока инструмент пишет журналы использования",
    "Alert threshold": "Порог уведомлений",
    "Alert when less than": "Уведомлять, когда осталось меньше",
    "Used by Almost out": "Для уведомления «Почти закончился»",
    "Per provider": "По сервисам",
    "Review": "Посмотреть",
    "Got it": "Понятно",
    "Panel": "Панель",
    "Move the widget in panel edit mode.": "Переместить виджет можно в режиме редактирования панели.",
    "Panel shows": "На панели",
    "What sits in the panel": "Что показывается на панели",
    "Limits in the panel": "Лимиты на панели",
    "Indicator": "Индикатор",
    "The mark in front of each figure": "Значок перед каждым числом",
    "Privacy": "Конфиденциальность",
    "Status pages": "Страницы статуса",
    "Show provider incidents from public status pages": "Показывать сбои сервисов с их публичных страниц статуса",
    "Quiet hours": "Тихие часы",
    "Held notifications arrive together when quiet hours end.": "Отложенные уведомления придут вместе, когда тихие часы закончатся.",
    "Hold notifications while you are away": "Откладывать уведомления, пока вас нет",
    "From": "С",
    "To": "До",
    "Still show critical alerts": "Всё равно показывать важные",
    "Will run out and Almost out come through": "«Закончится» и «Почти закончился» приходят сразу",
    "Reset all settings?": "Сбросить все настройки?",
    "Accounts stay signed in; appearance, notifications and hidden limits return to defaults.": "Вход в аккаунты сохранится; внешний вид, уведомления и скрытые лимиты вернутся к значениям по умолчанию.",
    "Reset": "Сбросить",
    "Keyboard": "Клавиатура",
    "Headroom can't store this shortcut. Try a letter, digit or function key with modifiers.": "Headroom не может сохранить это сочетание. Попробуйте букву, цифру или функциональную клавишу с модификаторами.",
    "This shortcut replaces the one on the widget's Keyboard Shortcuts page.": "Это сочетание заменяет заданное на странице «Комбинации клавиш» виджета.",
    "Open Headroom": "Открыть Headroom",
    "Opens the popup from any app": "Открывает окно из любого приложения",
    "Spend": "Расходы",
    "Show spend": "Показывать расходы",
    "Spend ring for all tools at the top of the popup": "Кольцо расходов по всем инструментам вверху окна",
    "Default period": "Период по умолчанию",
    "The tab the spend ring opens on": "Вкладка, с которой открывается кольцо расходов",
    "Units": "Единицы",
    "Breakdown on hover": "Разбивка при наведении",
    "What a spend legend row splits into": "На что делится строка легенды расходов",
    "RUST_LOG is set and wins over this setting": "Задана переменная RUST_LOG, она важнее этой настройки",
    "Debug adds provider responses without tokens": "«Отладка» добавляет ответы сервисов без токенов",
    "The service writes no log file": "Служба не пишет файл журнала",
    "A limit drops under {percent}% left": "Остаток лимита опускается ниже {percent}%",
    "Every provider uses the default": "Все сервисы используют общий порог",
    "{list} and {last}": "{list} и {last}",
    "Welcome to Headroom": "Добро пожаловать в Headroom",
    "Welcome to Headroom — we found {providers}": "Добро пожаловать в Headroom — нашли {providers}",
    "Review what shows in the panel and popup, or keep the defaults.": "Проверьте, что показывается на панели и в окне, или оставьте как есть.",
    "None chosen · the two most critical are shown": "Ничего не выбрано · показываются два самых критичных",
    "{count} of {max} chosen · shown in this order": "Выбрано {count} из {max} · в этом порядке",
    "Always open": "Всегда открыт",
    "On demand": "По запросу",
    "{count} provider differs from the default": ["{count} сервис отличается от общего порога", "{count} сервиса отличаются от общего порога", "{count} сервисов отличаются от общего порога"],
    "Show models and projects": "Показывать модели и проекты",
    "Top models and projects under the spend ring": "Топ моделей и проектов под кольцом трат",
    "Sign in again": "Войти снова",
    "Opens a terminal to renew the sign-in for this account": "Откроет терминал, чтобы обновить вход в этот аккаунт",
    "Links": "Ссылки",
    "Hidden accounts keep updating but leave the panel and notifications.": "Скрытые аккаунты продолжают обновляться, но не показываются на панели и в уведомлениях.",
    "Card in the popup": "Карточка во всплывающем окне",
    "Unstar": "Убрать звезду",
    "Star": "Отметить звездой",
    "Shown instead of the email": "Показывается вместо почты",
    "Position in the popup": "Место во всплывающем окне",
    "{position} of {count}": "{position} из {count}",
    "Move up": "Выше",
    "Move down": "Ниже",
    "Hidden limits leave the popup, the panel and notifications.": "Скрытые лимиты не показываются во всплывающем окне, на панели и в уведомлениях.",
    "Add Account…": "Добавить аккаунт…",
    "Signed out": "Выполнен выход",
    "Couldn't refresh": "Не удалось обновить"
};
